/* eslint-disable @typescript-eslint/no-unused-vars */
/**
 * 该文件由脚本自动生成，如需修改请联系 PMC
 * This file generated by scripts of tdesign-api. `npm run api:docs Tree React(PC) vitest,finalProject`
 * If you need to modify this file, contact PMC first please.
 */
import React from 'react';
import { mockDelay } from '@test/utils';
import { Tree } from '..';
import { getTreeDefaultMount } from './mount';

describe('Tree Component', () => {
  it('props.actived works fine', async () => {
    const wrapper = getTreeDefaultMount(Tree, { actived: [1] });
    const container = wrapper.container.querySelector('.t-tree__item:first-child');
    await mockDelay(300);
    console.log(wrapper.container.outerHTML);
    expect(container).toHaveClass('t-is-active');
    expect(container).toMatchSnapshot();
  });
});
